services:
  - type: web
    name: guntflix
    runtime: node
    repo: https://github.com/gunt/GuntFlix_MovieApp
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: SUPABASE_URL
        value: https://jknpkcxirqikdujhgcdl.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 22
